name: Docker-Publish

on:
  push:
    tags: ["v*.*.*"]      # publish on version tag
  workflow_dispatch:

permissions:
  contents: read
  packages: write         # push to GHCR
  id-token: write         # OIDC for cosign

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔨 Build container
        run: docker build -t $IMAGE:${GITHUB_REF##*/} .

      - name: 🔐 Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚚 Push image
        run: docker push $IMAGE:${GITHUB_REF##*/}

      - name: 🔐 Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: ✅ Sign image with Cosign
        run: cosign sign --yes $IMAGE:${GITHUB_REF##*/}
