apiVersion: v1
kind: Service
metadata:
  name: loan-risk-service
  labels:
    app.kubernetes.io/name: loan-risk
spec:
  selector:
    app.kubernetes.io/name: loan-risk
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
